name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release_chart:
    name: Release Helm Chart
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Get release tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout helm-charts
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: RomanMelnyk113/actions-test 
          path: helm-charts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Pushes to public repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
        env:
          API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
        with:
          source-directory: helm-charts/
          destination-github-username: "$GITHUB_ACTOR"
          destination-repository-name: "RomanMelnyk113/actions-test"
          user-email: "$GITHUB_ACTOR@users.noreply.github.com" 
          commit-message: pushed from $GITHUB_REF
          target-branch: main

      - name: Configure Git for helm-charts
        run: |
          pwd
          ls -l
          cd helm-charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout main
          ls -l
          cp -r ../charts .
          git add .
          ls -l
          git commit -m "[Release] Update chart"
          git push

