name: Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release_chart:
    name: Release Helm Chart
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - name: Get release tag
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout helm-charts
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: RomanMelnyk113/actions-test 
          path: helm-charts
          token: ${{ secrets.TEST_GITHUB_TOKEN }}

      - name: Configure Git for helm-charts
        run: |
          pwd
          echo "ls -l" && ls -l
          echo $GITHUB_REF >> Chart.yaml
          echo "cd helm-charts" && cd helm-charts
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout egressd
          echo "ls -l" && ls -l
          echo "cp -r ../charts ." && cp -r ../charts .
          git add .
          echo "ls -l" && ls -l
          git commit -m "[Release] Update chart"
          git push

